# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

# what is the name of this workflow
name: .NET

# When does this run?
on:
# Run, Whenever there is a push to main branch
  push:
    branches: [ "main" ]
# Run whenever there is a pull request merging to main
  pull_request:
    branches: [ "main" ]
    
# Manually trigger this workflow
  workflow_dispatch:
# What should this workflow do?
jobs:
# Name for the job. This jobs name is "build"
  build:
# What kind of VM is this running on?
    runs-on: ubuntu-latest
# Explicit instructions for the runner/vm to execute
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
